### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by yousifKashef** [freakboy3742/chaquopy#8]

**Comment by yousifKashef** [comment]
It would b great have pytorch on iOS. I am happy to help et this up

**Comment by freakboy3742** [comment]
If you want to try to work on a recipe for PyTorch, you're welcome to do so and submit as a pull request. 

FWIW: The reason there isn't currently an iOS package for PyTorch (see the `torch` recipe) is that there is a dependency on libfortran, and I haven't found a Fortran compiler that can produce iOS compatible output. If you can resolve that, there's a bunch of packages that become viable.

Also: We're in the process of moving the functionality of this repository to a more permanent home - https://github.com/beeware/mobile-forge - when the next release of Briefcase lands, that's where we will manage all the binary wheels.

**Comment by yousifKashef** [comment]
Are there instructions about how to compile a package for iOS? Also it would be great if you can guide me about how to resolve that compiler issue

**Comment by freakboy3742** [comment]
If I had instructions for how to compile PyTorch, they'd be baked into the recipe already. If I knew of a Fortran compiler, I'd already be using it.

This is literally an exploration task. The instructions for use of the mobile-forge repo are in the README; beyond that, you're in new territory.

**Comment by freakboy3742** [comment]
Closed in favor of beeware/mobile-forge#7
